name: AxInventoryRestore
version: '${project.version}'
main: com.artillexstudios.axinventoryrestore.AxInventoryRestore
api-version: '1.19'
folia-supported: true

softdepend:
  - LuckPerms
  - AxShulkers

permissions:
  axinventoryrestore.view:
    default: op
  axinventoryrestore.modify:
    default: op
  axinventoryrestore.teleport:
    default: op
  axinventoryrestore.restore:
    default: op
  axinventoryrestore.export:
    default: op
  axinventoryrestore.reload:
    default: op
  axinventoryrestore.manualbackup:
    default: op
  axinventoryrestore.cleanup:
    default: op
  axinventoryrestore.admin:
    default: op
  axinventoryrestore.discord-request:
    default: op

libraries:
  - net.dv8tion:JDA:5.2.2
  - club.minnced:discord-webhooks:0.8.4