name: AxInventoryRestore
version: '${project.version}'
main: com.artillexstudios.axinventoryrestore.AxInventoryRestore
api-version: '1.13'

commands:
  axinventoryrestore:
    usage: /<command>
    aliases: [axir]

permissions:
  axinventoryrestore.view:
    default: op
  axinventoryrestore.modify:
    default: op
  axinventoryrestore.teleport:
    default: op
  axinventoryrestore.restore:
    default: op
  axinventoryrestore.export:
    default: op
  axinventoryrestore.reload:
    default: op
  axinventoryrestore.manualbackup:
    default: op
  axinventoryrestore.cleanup:
    default: op
  axinventoryrestore.admin:
    default: op
  axir.view:
    default: op
  axir.modify:
    default: op
  axir.teleport:
    default: op
  axir.restore:
    default: op
  axir.export:
    default: op
  axir.reload:
    default: op
  axir.manualbackup:
    default: op
  axir.cleanup:
    default: op
  axir.admin:
    default: op

libraries:
  - com.mysql:mysql-connector-j:8.0.33
  - org.xerial:sqlite-jdbc:3.42.0.0
#  - com.h2database:h2:2.1.214
#  - org.postgresql:postgresql:42.5.4